### ISSUE TITLE
decap, writing less data to xdp

### ISSUE THREAD

**Issue by williamtu** [williamtu/p4c-xdp#13]
This error happens when not emitting ethernet header
when testing the same case without icmp hader, it works OK.

```
control Deparser(in Headers hdrs, packet_out packet) {
    apply {
        //packet.emit(hdrs.ethernet);
        packet.emit(hdrs.ipv4);
        packet.emit(hdrs.icmp);
    }   
}
```

BPF verifier

```
R0=imm0,min_value=0,max_value=0 R1=pkt(id=0,off=0,r=4) R2=pkt_end R3=fp-12 R4=imm4,min_value=4,max_value=4 R5=pkt(id=0,off=4,r=4) R6=ctx R7=imm0,min_value=0,max_value=0 R8=inv,min_value=0,max_value=0 R9=inv R10=fp
269: (bf) r2 = r0
270: (77) r2 >>= 3
271: (bf) r4 = r1
272: (0f) r4 += r2
addition of negative constant to packet pointer is not allowed
```

LLVM objdump
```
; if (hd.icmp.ebpf_valid) {
     261:	r4 = *(u64 *)(r10 - 40)
     262:	if r4 == 0 goto 29
; if (ebpf_packetEnd < ebpf_packetStart + BYTES(ebpf_packetOffsetInBits + 32)) {
     263:	r4 = r0
     264:	r4 += 32
     265:	r4 >>= 3
     266:	r5 = r1
     267:	r5 += r4
     268:	if r5 > r2 goto 23
; write_byte(ebpf_packetStart, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte) << 0);
     269:	r2 = r0
     270:	r2 >>= 3
     271:	r4 = r1
     272:	r4 += r2
     273:	r2 = *(u64 *)(r10 - 80)
     274:	*(u8 *)(r4 + 0) = r2
; ebpf_packetOffsetInBits += 8;
     275:	r0 |= 8
; write_byte(ebpf_packetStart, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte) << 0);
     276:	r2 = r0
```

**Comment by mbudiu-vmw** [comment]
Which program are you compiling to get this error?
We should add the xdp.p4 and xdp1.p4 files to the tests.

I just submitted a PR; the old ebpf programs were crashing the compiler for me.

**Comment by mbudiu-vmw** [comment]
You should commit the modified program as a test as well.
I don't see any negative constant in the C program.

**Comment by williamtu** [comment]
thanks, I've pushed the code, please see tests/xdp3.p4
both xdp1 and xdp2 pass, but xdp3 fail
I guess some verifier issues?

**Comment by mbudiu-vmw** [comment]
Unfortunately I don't have the other bpf patch you submitted, so my verifier fails with the old problem:

cannot add integer value with 0 upper zero bits to ptr_to_packet

Do you suggest for me to apply the patch to the kernel and recompile it?

**Comment by williamtu** [comment]
sure, I will send you the patch.

**Comment by williamtu** [comment]
[xdp3.S.txt](https://github.com/williamtu/p4c-xdp/files/748679/xdp3.S.txt)

**Comment by mbudiu-vmw** [comment]
This looks to me like a bug in the verifier:
```
		if (imm <= 0) {
			verbose("addition of negative constant to packet pointer is not allowed\n");
			return -EACCES;
		}
```

The test should be `imm < 0`

**Comment by williamtu** [comment]
thanks! yes you're right... R0 is zero
```
R0=imm0,min_value=0,max_value=0 R1=pkt(id=0,off=0,r=4) R2=pkt_end R3=fp-12 R4=imm4,min_value=4,max_value=4 R5=pkt(id=0,off=4,r=4) R6=ctx R7=imm0,min_value=0,max_value=0 R8=inv,min_value=0,max_value=0 R9=inv R10=fp
269: (bf) r2 = r0
270: (77) r2 >>= 3
271: (bf) r4 = r1
272: (0f) r4 += r2
```

**Comment by mbudiu-vmw** [comment]
You can try to patch the verifier and see what happens.
You should also report this bug...

**Comment by williamtu** [comment]
patch submitted
https://patchwork.ozlabs.org/patch/723281/
