### ISSUE TITLE
xdp5.p4 and xdp6.p4: xout.drop not initialized

### ISSUE THREAD

**Issue by williamtu** [williamtu/p4c-xdp#19]
In xdp5.p4, initialize xoutdrop to false
```C
control Ingress(inout Headers hd, in xdp_input xin, out xdp_output xout) {
    bool xoutdrop = false;
```

but the generated xdp5.c does not initialize it, causing the following verifier error:
```C
 R0=inv,min_value=0,max_value=0 R2=imm272,min_value=272,max_value=272 R3=imm0,min_value=0,max_value=0 R4=inv,min_value=0,max_value=0 R6=ctx R7=imm34,min_value=34,max_value=34 R8=inv56 R9=inv56 R10=fp
171: (b7) r2 = 112
172: (63) *(u32 *)(r10 -12) = r3
173: (73) *(u8 *)(r10 -16) = r1
R1 !read_ok
Makefile:54: recipe for target 'xdp5.o' failed
```
llvm-objdump
```C
; xout.output_port = 0;
     172:	*(u32 *)(r10 - 12) = r3
; xout.drop = xoutdrop;
     173:	*(u8 *)(r10 - 16) = r1
; bpf_xdp_adjust_head(skb, BYTES(ebpf_packetOffsetInBits) - ebpf_outHeaderLength);
     174:	r7 -= r2
     175:	r1 = r6
```

**Comment by mbudiu-vmw** [comment]
The output is actually correct - assuming that the action in the table is one of Fallback_action or Drop_action. But the verifier does not trust that the switch statement covers all possible cases. So I will need to generate a default label for the switch statement.

**Comment by williamtu** [comment]
I've applied your fix, it works for xdp5.p4. I wrote another test, xdp6.p4, but it fails. for xdp6.p4, Not sure whether it's my mistake on the P4 syntax or a bug.

**Comment by mbudiu-vmw** [comment]
What is the failure you see for xdp6?
I get this:

./bpfloader xdp6.o
failed to create a map: 22 Invalid argument

**Comment by williamtu** [comment]
clang \
-D__KERNEL__ -D__ASM_SYSREG_H -Wno-unused-value -Wno-pointer-sign \
-Wno-compare-distinct-pointer-types \
-Wno-gnu-variable-sized-type-not-at-end \
-Wno-tautological-compare \
-O2 -emit-llvm -g -c xdp6.c -o -| llc -march=bpf -filetype=obj -o xdp6.o
./bpfloader xdp6.o
bpf_prog_load() err=13
...
259: (18) r1 = 0xa859f100
261: (b7) r4 = 0
262: (85) call bpf_map_update_elem#2
263: (b7) r0 = 2
264: (71) r1 = *(u8 *)(r10 -16)
invalid read from stack off -16+0 size 1

**Comment by mbudiu-vmw** [comment]
I think I need to change the behavior of the deparser:

                if (ebpf_packetEnd < ebpf_packetStart + BYTES(ebpf_packetOffsetInBits + 160)) {
                    ebpf_errorCode = PacketTooShort;
                    goto ebpf_end;
                }

This should terminate with return XDP_ABORT instead.

**Comment by mbudiu-vmw** [comment]
Please let me know if this change solves the problem.

**Comment by williamtu** [comment]
with this change at deparser in xdp6.c (2 places)
```C
                if (ebpf_packetEnd < ebpf_packetStart + BYTES(ebpf_packetOffsetInBits + 112)) {
                    ebpf_errorCode = PacketTooShort;
                    return XDP_ABORTED;
                }
```
no. still the same error. I guess the code path of executing "case SetTTL_action:" causes the xout.drop not initialized.

```C
     if (value != NULL) {
                    /* run action */
                    switch (value->action) {
                        case Fallback_action:
                        {
                            xout.drop = false;
                        }
                        break;
                        case Drop_action:
                        {
                            xout.drop = true;
                        }
                        break;
                        case SetTTL_action:
                        { 
                            hd.ipv4.ttl = value->u.SetTTL_action.md.ttl;
                        } 
                        break;
                        default: return XDP_ABORTED;
                    }
                }
                else return XDP_ABORTED;
            }
;   
            xout.output_port = 0;
```

**Comment by mbudiu-vmw** [comment]
What if you set drop as well on all paths?
I expect that won't help, since you are not indexing in the output table with this field.

**Comment by williamtu** [comment]
setting xout.drop in all switch case works. 
for xdp6.c, add this one line
```C
--- a/tmp/xdp6.c
+++ b/tmp/xdp6.c.0
@@ -243,6 +243,7 @@ int ebpf_filter(struct xdp_md* skb){
                         break;
                         case SetTTL_action: 
                         {
+                            xout.drop = true;
                             hd.ipv4.ttl = value->u.SetTTL_action.md.ttl;
                         }
                         break;

```

**Comment by mbudiu-vmw** [comment]
The p4 program is the problem; please add this statement in the action, and the compiler will emit it in the output.

**Comment by williamtu** [comment]
oh, I see. thanks. test it and found no problem.
