### ISSUE TITLE
default_action map does not get populated

### ISSUE THREAD

**Issue by williamtu** [williamtu/p4c-xdp#20]
When setting default_action in p4, we create a map and look it up the index 0 entry "bpf_map_lookup_elem(&dstmactable_defaultAction, &ebpf_zero);"
but we don't actually populate this map entry with the default action.
Now it always assumes the first entry in actions as default.

Not critical issue. I could work around it by putting the default at index 0

```C
control Ingress(inout Headers hd, in xdp_input xin, out xdp_output xout) {
    action SetTTL_action(action_md_t md) 
    {   
        hd.ipv4.ttl = md.ttl;
    }   
    action Fallback_action()
    {   
        xout.drop = false;
    }   
    action Drop_action()
    {   
        xout.drop = true;
    }   
    table dstmactable() {
        key = { hd.ethernet.protocol : exact; }
        actions = { 
            SetTTL_action;      // miss will trigger this one index 0
            Fallback_action;
            Drop_action;
        }
        default_action = Drop_action;  // default entry at index 2 
        implementation = hash_table(64);
    }   
    apply {
        dstmactable.apply();
        xout.output_port = 0;
    }   
}
```

**Comment by mbudiu-vmw** [comment]
All maps are populated by the control plane.
I don't know if you can add entries to a BPF table at compile-time.

**Comment by williamtu** [comment]
you are right. It should be set by the control plane. let's worry about it later.
