### ISSUE TITLE
xdp8.p4: ip csum update

### ISSUE THREAD

**Issue by williamtu** [williamtu/p4c-xdp#23]
I forgot whether we want to do csum update at this moment or later. But let me keep track of it.
xdp8.p4 will by default write ttl=4, and my working implementation of csum update is below
```C
--- a/tmp/xdp8.c
+++ b/tmp/xdp8.c.0
@@ -309,10 +309,16 @@ int ebpf_filter(struct xdp_md* skb){
 ;
             /* packet.emit(hd.ipv4)*/
             if (hd.ipv4.ebpf_valid) {
+                u32 csum = 0, i = 0;
+                u16 *iph;
+
                 if (ebpf_packetEnd < ebpf_packetStart + BYTES(ebpf_packetOffsetInBits + 160)) {
                     ebpf_errorCode = PacketTooShort;
                     goto ebpf_end;
                 }
+
+                iph = (u16 *)(ebpf_packetStart + BYTES(ebpf_packetOffsetInBits));
+
                 ebpf_byte = ((char*)(&hd.ipv4.version))[0];
                 write_byte(ebpf_packetStart, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte) << 4);
                 ebpf_packetOffsetInBits += 4;
@@ -374,6 +380,13 @@ int ebpf_filter(struct xdp_md* skb){
                 ebpf_byte = ((char*)(&hd.ipv4.dstAddr))[3];
                 write_byte(ebpf_packetStart, BYTES(ebpf_packetOffsetInBits) + 3, (ebpf_byte) << 0);
                 ebpf_packetOffsetInBits += 32;
+
+                /* update csum, the ip csum is at 10 byte offset */
+                *(iph + 5) = 0;
+                for (i = 0; i < (20>>1); i++)
+                    csum += iph[i];
+
+                *(iph + 5) = ~((csum & 0xffff) + (csum >> 16));
             }
 ;
         }
```

**Comment by mbudiu-vmw** [comment]
I plan to provide exactly 1 function:

extern bit<16> ipv4checksum(bit<4> version, bit<4> ihl, ...) - i.e., all necessary fields.

**Comment by williamtu** [comment]
need this patch, I've pushed to master.

--- a/xdpProgram.cpp
+++ b/xdpProgram.cpp
@@ -133,7 +133,8 @@ void XDPProgram::emitC(EBPF::CodeBuilder* builder, cstring headerFile) {
         "    dstAddr = htonl(dstAddr);\n"
         "    checksum += (srcAddr >> 16) + (u16)srcAddr;\n"
         "    checksum += (dstAddr >> 16) + (u16)dstAddr;\n"
-        "    return ~((checksum & 0xFFFF) + (checksum >> 16));\n"
+        "    // Fields in 'struct Headers' are host byte order. Deparser converts to network byte-order\n"
+        "    return __constant_ntohs(~((checksum & 0xFFFF) + (checksum >> 16)));\n"
         "}");
