### ISSUE TITLE
xdp11.p4: swap ether src dst, return XDP_TX

### ISSUE THREAD

**Issue by williamtu** [williamtu/p4c-xdp#28]
try to mimic the same behavior as sample/bpf/xdp2_kern.c
which swaps the ether src and dst, then output to the same port
It works ok, however, there is no way to return XDP_TX

currently depends on xout.drop then return XDP_DROP or XDP_PASS
XDP_TX tells the driver to send the packet to the same port as receiving. 
should we allow P4 programmer to say "return XDP_TX" ?

**Comment by mbudiu-vmw** [comment]
If you want more return values we must change the architecture file.

**Comment by mbudiu-vmw** [comment]
Should we build this feature?
This will change the architecture by adding an enum XdpAction { XDP_DROP, XDP_PASS, XDP_TX }.
Then the structure xdp_out will have a field with this value instead of a bool.
So you will have to change all your P4 programs.

**Comment by williamtu** [comment]
yes, let's do it this way.
enum XdpAction should have 4 
{ XDP_ABORTED=0, XDP_DROP, XDP_PASS, XDP_TX }

**Comment by mbudiu-vmw** [comment]
The last PR #31 should solve this issue.
