### ISSUE TITLE
p4c-xdp: treat warning as error

### ISSUE THREAD

**Issue by williamtu** [williamtu/p4c-xdp#40]
not urgent at all but is there a way to treat warning as error, so the shell returns non-zero?
for example:
```shell
# make
 ../p4c-xdp -I ../p4include --target xdp -o xdp14.c xdp14.p4;
xdp14.p4(90): warning: action_md.output.port may be uninitialized
        outport = action_md.output.port;
```
I want the "make" stops when seeing this warning. So that the travis-ci could report build failed.

**Comment by mbudiu-vmw** [comment]
Added --Werror option in p4c-clone; pending merge into p4c upstream.

**Comment by williamtu** [comment]
tested on p4c and works OK, thanks!
