### ISSUE TITLE
TCP csum incorrect: xdp7.p4

### ISSUE THREAD

**Issue by williamtu** [williamtu/p4c-xdp#42]
Should we make the current ipv4 csum implementation generic to support tcp/udp/ipv6 csum?

**Comment by williamtu** [comment]
I see... How does p4c bmv switch solve this problem? Can we reuse some of their code?

**Comment by mbudiu-vmw** [comment]
Actually for a very long time they did not handle TCP checksums correctly, I don't even know if they do today.

They have a special construct for checksums called "payload", but I am not sure that the compiler supports it on their real ASIC target, on the simulator it is easy. We'll have to do it ourselves incrementally.

**Comment by williamtu** [comment]
Ok
Let me first work on a C version, then send to you.

**Comment by williamtu** [comment]
I've updated the p4c-xdp, see the latest commit.

**Comment by mbudiu-vmw** [comment]
This is fine as long as you update aligned 16-bit fields.
May be good enough for all our needs.

**Comment by williamtu** [comment]
I also add support for updating 32-bit field (csum_replace4), I think this at lease meets the NAT case.
